name: a test workflow

on : 
    push:
        branches: ["main"]

jobs: 
    testing-testing:
        runs-on : ubuntu-latest
        steps:

            #steps under the job are a follows
           - name: welcome people
             run: echo "welcome to class"

            #step2
           - name: tell people goodbye
             run: echo "goodbye class"